### ISSUE TITLE
Error in groopm parse

### ISSUE THREAD

**Issue by bstamps** [Ecogenomics/GroopM#12]
Trying to run groopm parse (And I think I'm all installed correctly!) But I keep running into this error- any ideas? 

groopm parse ConePool Scaffolds_ConePoolCo.fasta *.bam -t 8

Parsing contigs
Parsing BAM files using 8 threads
Error creating database: ConePool <type 'exceptions.NameError'>
Unexpected error: <type 'exceptions.NameError'>
Traceback (most recent call last):
  File "/usr/local/bin/groopm", line 381, in <module>
    GM_parser.parseOptions(args)
  File "/usr/local/lib/python2.7/dist-packages/groopm/groopm.py", line 117, in parseOptions
    threads=options.threads)
  File "/usr/local/lib/python2.7/dist-packages/groopm/mstore.py", line 275, in createDB
    threads)
  File "/usr/local/lib/python2.7/dist-packages/groopm/mstore.py", line 1734, in parse
    verbose=True)
  File "/usr/local/lib/python2.7/dist-packages/bamm/bamParser.py", line 349, in parseBams
    raise BAMIndexNotFoundException("Index file %s not found" % \
NameError: global name 'BAMIndexNotFoundException' is not defined

**Comment by wwood** [comment]
Hi,

Thanks for trying GroopM. Are your bam files sorted and indexed?

**Comment by bstamps** [comment]
That did it- next error (Feeling like a total noob here at the moment...)- 

 groopm core -c 500 ConePool.gm 
*******************************************************************************
 [[GroopM 0.3.4]] Running in core creation mode...
*******************************************************************************
Loading data from: ConePool.gm
    GroopM DB version (5) up to date
Error opening DB: ConePool.gm <type 'exceptions.ValueError'>
Error loading DB: ConePool.gm <type 'exceptions.ValueError'>
Unexpected error: <type 'exceptions.ValueError'>
Traceback (most recent call last):
  File "/usr/local/bin/groopm", line 381, in <module>
    GM_parser.parseOptions(args)
  File "/usr/local/lib/python2.7/dist-packages/groopm/groopm.py", line 138, in parseOptions
    gf=gf)
  File "/usr/local/lib/python2.7/dist-packages/groopm/cluster.py", line 191, in makeCores
    self.PM.loadData(self.timer, "length >= "+str(coreCut))
  File "/usr/local/lib/python2.7/dist-packages/groopm/profileManager.py", line 189, in loadData
    silent=silent)
  File "/usr/local/lib/python2.7/dist-packages/groopm/mstore.py", line 959, in getConditionalIndices
    return np.array([x.nrow for x in h5file.root.meta.contigs.where(condition)])
  File "/usr/lib/python2.7/dist-packages/tables/table.py", line 1420, in where
    return self._where(condition, condvars, start, stop, step)
  File "/usr/lib/python2.7/dist-packages/tables/table.py", line 1437, in _where
    compiled = self._compileCondition(condition, condvars)
  File "/usr/lib/python2.7/dist-packages/tables/table.py", line 1316, in _compileCondition
    compiled = compile_condition(condition, typemap, indexedcols, copycols)
  File "/usr/lib/python2.7/dist-packages/tables/conditions.py", line 391, in compile_condition
    func = NumExpr(expr, signature, copy_args=copycols)
  File "/usr/local/lib/python2.7/dist-packages/numexpr/necompiler.py", line 552, in NumExpr
    context = getContext(kwargs, frame_depth=1)
  File "/usr/local/lib/python2.7/dist-packages/numexpr/necompiler.py", line 473, in getContext
    raise ValueError("Unknown keyword argument '%s'" % d.popitem()[0])
ValueError: Unknown keyword argument 'copy_args'

**Comment by wwood** [comment]
Nasty, I think you may have old version(s) of numexpr or pytables? see e.g.
https://github.com/PyTables/PyTables/issues/283

Can you try upgrading?

**Comment by bstamps** [comment]
I am a ball of trouble tonight- updated PyTables and now I'm getting a new error- I can't run parse again...

*******************************************************************************
 [[GroopM 0.3.4]] Running in data parsing mode...
*******************************************************************************
Creating new database ConePool.gm
Error creating database: ConePool.gm <type 'exceptions.AttributeError'>
Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/usr/local/bin/groopm", line 381, in <module>
    GM_parser.parseOptions(args)
  File "/usr/local/lib/python2.7/dist-packages/groopm/groopm.py", line 117, in parseOptions
    threads=options.threads)
  File "/usr/local/lib/python2.7/dist-packages/groopm/mstore.py", line 229, in createDB
    with tables.openFile(dbFileName, mode = "w", title = "GroopM") as h5file:
AttributeError: 'module' object has no attribute 'openFile'

**Comment by wwood** [comment]
Hmm,

I think this may point to a larger error in GroopM, that it is expecting pytables 2.x but it is being given 3.x. Perhaps the easiest thing for you would be to install the dependencies as listed below, maybe easiest within a virtualenv. This is what we use at ACE.
```
module		 load pytables/2.3.1 
module		 load numpy/1.9.0 
module		 load scipy/0.14.0 
module		 load matplotlib/1.3.1 
module		 load bamm/1.3.8 
```
We should update the setup.py of GroopM should be updated I think limiting its version numbers, in lieu of a pytables 2->3 conversion of the code.

Apologies for the mess.

**Comment by bstamps** [comment]
OK- ended up creating a GroopM Amazon VM. Everything is golden, with one minor problem now as I try to create plots. Since I have no $DISPLAY variable set I get- 

Loading data from: db.gm
    GroopM DB version (5) up to date
    Loaded indices with condition: ((length >= 0) & (bid != 0))
    Working with: 7641 contigs
    Loading coverage profiles
    Loading PCA kmer sigs (18 dimensional space)
    Loading PCA kmer variance (total variance: 0.80)
    Loading contig lengths (Total: 63538822 BP)
    Loading contig GC ratios (Average GC: 0.563)
    Creating color map
    Loading bin assignments
    Reticulating splines
    Making bin objects
    Loaded 32 bins from database
    { THIS: 0:00:03.211 || TOTAL: 0:00:03.211 }
Plotting bins
Unexpected error: <class '_tkinter.TclError'>
Traceback (most recent call last):
  File "/usr/local/bin/groopm", line 381, in <module>
    GM_parser.parseOptions(args)
  File "/usr/local/lib/python2.7/dist-packages/groopm/groopm.py", line 265, in parseOptions
    folder=options.folder)
  File "/usr/local/lib/python2.7/dist-packages/groopm/binManager.py", line 1381, in plotBins
    ignoreContigLengths=ignoreContigLengths, ET=ET)
  File "/usr/local/lib/python2.7/dist-packages/groopm/bin.py", line 490, in plotBin
    fig = plt.figure()
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 423, in figure
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 87, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

Is there a simple fix to this one?

**Comment by wwood** [comment]
Good you got further, but gah. Hmm, do you mind posting the command line you used please, or email me privately if you are wanting privacy. Thanks.

**Comment by bstamps** [comment]
Fixed! 

You need to modify /etc/matplotlibrc to use 'Agg' as the backend instead of 'TkAgg' if you have no X server as per http://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined . 

I think the only command I'm SOL on without a GUI is refine, but it will serve the purposes of the course! Running CheckM post-binning the make sure we aren't too contaminated of course. 

Thank you for the help!

**Comment by wwood** [comment]
Excellent, thank you for reporting that back here. You just helped someone else.

**Comment by prehensilecode** [comment]
PyTables 2.4.0 is obsolete, and its setup.py does not handle numpy version number checking properly. https://github.com/PyTables/PyTables/issues/601

Here's a fix for it:

https://gist.github.com/prehensilecode/2eb790476c38299e520ce5ea40896e08

**Comment by wwood** [comment]
Thanks for the tip, although the issue you describe seems a little off-topic for this exact thread. In the new version of GroopM, we have moved to PyTables 3.

**Comment by prehensilecode** [comment]
Well, groopm/mstore.py still uses tables.openFile() which is the PyTables 2.x method name. The PyTables 3 method name is tables.open_file(). So, it does not seem that GroopM in the master branch of this repo has been updated to PyTables 3.

See the PyTables 2->3 migration guide: https://www.pytables.org/MIGRATING_TO_3.x.html

I will submit a pull request later today.
