### ISSUE TITLE
Error while using groopm core

### ISSUE THREAD

**Issue by mchaib** [Ecogenomics/GroopM#19]
Hello, 
I have successfully created a database using groopm parse using my contigs and the mapped raw reads. Then, I tried using groopm core, but at some point I get an error. See below. Could you please indicate what the problem may be?
Thank you!

*******************************************************************************
 [[GroopM 0.3.4]] Running in core creation mode...
*******************************************************************************
Loading data from: database.gm
    GroopM DB version (5) up to date
    Loaded indices with condition: length >= 1500
    Working with: 156422 contigs
    Loading coverage profiles
    Loading PCA kmer sigs (43 dimensional space)
    Loading PCA kmer variance (total variance: 0.80)
    Loading contig names
    Loading contig lengths (Total: 522276132 BP)
    Loading contig GC ratios (Average GC: 0.586)
    Creating color map
    { THIS: 0:01:55.423 || TOTAL: 0:01:55.436 }
    Loading transformed data
    Reticulating splines
    { THIS: 0:00:17.960 || TOTAL: 0:02:13.396 }
Create cores
     .... .... .... .... .... .... .... .... .... ....
   0  3461   74  356  3060  15311  1826   10   18   82  6896
  10   35  198   43   20   25   74   13   58  2563   74
  20  649  346  1210  1762  1507   12  1271    8  1089  1329
  30  100  2313   22  207   28  667  2179    7  1563  398
  40  1344  1440  1123    8   59  1437   62  186  1264   42
  50  2211  1237  580  2540   59  2748  788  431    3   22
  60   12  130  3576  306   36   80   38  747  3532  2083
  70  1589   21  645   31  1099    7   21   12  273    4
  80  1631  2898   11  186  166  191  664  416   28  1087
  90  603  1209  1215  469  550  597  1492  1334   57  815
 100  464   24  1015   11   64    8  149  103  294  712
 110   26  1095  987  1151   81  1813  606    9  1347   64
 120  276  494  1320  657   74  690  123  148   76  178
 130  766  560  977  570  439  756  189  663  452   16
 140  368  160   15   89  669  182  725  180   87  431
 150  211  101  292  212  290   63  103   61   94  330
 160  963   46   28  563   94  910  396  175  749  218
 170  244  102    4  112  132  343   43  679   75   39
 180  486  487  267  697   13  165   85   94   61  142
 190  112   18   49  109   40  200  334  102   25   90
 200   58   96  303  316  101   82  221   28   43  281
 210  430   32   43   76  273  100  176  473  436  298
 220  308  174  391  247   35  134   87   72  175   21
 230  155  253  117   29  350  148  155   73   34   46
 240   95   97   92   31  230   43  246   95   58   27
 250   82  129   63  211   90  125   55  581   56   27
 260  135   10  283   15   27   62  130   71   94  101
 270   50  177   33   81   59   53   83   49   49   46
 280  103  121   17   39  223  177  104  182  153   58
 290   94   40   49  202   15  128   87   12   49   76
 300  233   40  171  297  200   48   25   54  185  229
 310   40   19   15   47   23   36   17   26   46  121
 320  180   71   51   97  146   26    7  107  104   82
 330   29   60   73   79   58  284   11   55   66   19
 340   66   34   15   96   67   23   70   86   70   94
 350   25   38   49   79   21   54   11   90   26   60
 360  154   62   54  230
     .... .... .... .... .... .... .... .... .... ....
    { THIS: 4:35:07.126 || TOTAL: 4:37:20.523 }
Refine cores [begin: 364]
    Start automatic bin refinement
    149801 contigs across 364 cores ( 95.77 % )
    Identifying possible chimeric bins
    Identified 13 likely chimeric bin(s), removed 4 small chimeric bin(s)
    307,317,327,346
    { THIS: 0:00:00.818 || TOTAL: 4:37:21.341 }
    Merging similar bins (351) with kCut 39.33 (+/-4.972) cCut 0.23 (+/-0.115)
Unexpected error: <type 'exceptions.FloatingPointError'>
Traceback (most recent call last):
  File "/home/p270270/.local/bin/groopm", line 381, in <module>
    GM_parser.parseOptions(args)
  File "/home/p270270/.local/lib/python2.7/site-packages/groopm/groopm.py", line 138, in parseOptions
    gf=gf)
  File "/home/p270270/.local/lib/python2.7/site-packages/groopm/cluster.py", line 217, in makeCores
    self.RE.refineBins(self.timer, auto=True, saveBins=False, plotFinal=prfx, gf=gf)
  File "/home/p270270/.local/lib/python2.7/site-packages/groopm/refine.py", line 158, in refineBins
    graph = self.autoRefineBins(timer, makeGraph=gf!="")
  File "/home/p270270/.local/lib/python2.7/site-packages/groopm/refine.py", line 474, in autoRefineBins
    self.mergeSimilarBins(graph=graph, verbose=False)
  File "/home/p270270/.local/lib/python2.7/site-packages/groopm/refine.py", line 571, in mergeSimilarBins
    mergers = self.findMergeGroups(kCutMedian, kCutStd, cCutMedian, cCutStd, verbose=verbose)
  File "/home/p270270/.local/lib/python2.7/site-packages/groopm/refine.py", line 631, in findMergeGroups
    retA=True)
  File "/home/p270270/.local/lib/python2.7/site-packages/groopm/bin.py", line 352, in getBoundingKEllipseArea
    (A, center, radii, _rotation) = ET.getMinVolEllipse(KPCAs, retA=True)
  File "/home/p270270/.local/lib/python2.7/site-packages/groopm/ellipsoid.py", line 153, in getMinVolEllipse
    radii = 1.0/np.sqrt(s)
FloatingPointError: divide by zero encountered in divide

**Comment by timbalam** [comment]
Hi mchaib,
Thanks for opening the issue. This looks like a bug possibly triggered by a bin with no or a single member contig. Shouldn't be too hard to fix. I will try to get to it before the end of the week.
Regards,
Tim

**Comment by mchaib** [comment]
Dear Tim,
Thanks for your reply. I was wondering whether you had made any progress regarding the bug? Thanks again.
Maryam

**Comment by timbalam** [comment]
Hi Maryam,

I have written a patch that should stop the crash you saw. Hopefully it
will soon be pushed to the Ecogenomics github repository. Are you able
to build from that? Unfortunately we have had issues updating the GroopM
pip repository in the past if you are using that.

I'll let you know when the patch is merged into the Ecogenomics repository.

Let me know if you run into more issues!

Regards,
Tim

**Comment by mchaib** [comment]
Dear Tim,

Sounds good. Sure, just let me know when it is out. I should be able to take it from there.
Many thanks,
Maryam

**Comment by jvollme** [comment]
Hello,
I recently ran into the exact same problem (using GroopM v0.3.4 installed via pip). 
Has this issue already been fixed in the github repository?
Do you have instructions for building groopM from the repository instead of pip?
