### ISSUE TITLE
GroopM Core -stops

### ISSUE THREAD

**Issue by maria-456** [Ecogenomics/GroopM#21]
Hello,
I have downloaded GroopM and keep getting this error when I get to the groopm core step. I have tried re-mapping and recreating my bam files as well as reinstalling groopm and it's dependencies, but I still keep getting this error and can't figure out why!

`*******************************************************************************
 [[GroopM 0.3.4]] Running in core creation mode...
*******************************************************************************
Loading data from: groopm10.db
    GroopM DB version (5) up to date
    Loaded indices with condition: length >= 1500
    Working with: 13327 contigs
    Loading coverage profiles
    Loading PCA kmer sigs (10 dimensional space)
    Loading PCA kmer variance (total variance: 0.81)
    Loading contig names
    Loading contig lengths (Total: 90577575 BP)
    Loading contig GC ratios (Average GC: 0.488)
    Creating color map
    { THIS: 0:00:08.394 || TOTAL: 0:00:08.406 }
    Loading transformed data
    Reticulating splines
    { THIS: 0:00:01.369 || TOTAL: 0:00:09.775 }
Create cores
Unexpected error: <type 'exceptions.IndexError'>
Traceback (most recent call last):
  File "/media/acclomator/egraham/.local/bin/groopm", line 381, in <module>
    GM_parser.parseOptions(args)
  File "/media/acclomator/egraham/.local/lib/python2.7/site-packages/groopm/groopm.py", line 138, in parseOptions
    gf=gf)
  File "/media/acclomator/egraham/.local/lib/python2.7/site-packages/groopm/cluster.py", line 208, in makeCores
    self.initialiseCores(kmerThreshold, coverageThreshold)
  File "/media/acclomator/egraham/.local/lib/python2.7/site-packages/groopm/cluster.py", line 231, in initialiseCores
    self.populateImageMaps()
  File "/media/acclomator/egraham/.local/lib/python2.7/site-packages/groopm/cluster.py", line 914, in populateImageMaps
    self.incrementViaRowIndex(row_index, p)
  File "/media/acclomator/egraham/.local/lib/python2.7/site-packages/groopm/cluster.py", line 921, in incrementViaRowIndex
    self.incrementAboutPoint(0, point[0], point[1], multiplier=multiplier)
  File "/media/acclomator/egraham/.local/lib/python2.7/site-packages/groopm/cluster.py", line 952, in incrementAboutPoint
    self.imageMaps[view_index,px-1,py-1] += valC      # Top left corner
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
`

**Comment by timbalam** [comment]
Hi maria-456,

Thanks for the report!

I'm currently working on a new version of GroopM. As this is my focus, I
probably won't get around to fixing bugs such as this one in the current
version that aren't relevant to the new version.

The new version I think will be much better. I will let you know when it
is ready.

Cheers,
Tim

**Comment by maria-456** [comment]
I just wanted to let you know that I fixed my error. I had updated numpy when I did this and when I went back down to numpy v1.10.3 instead of numpy v1.11 everything worked fine. I forgot to update that in case anyone else has a similar issue!

**Comment by timbalam** [comment]
That's good to know. :) Thanks maria-456!
