### ISSUE TITLE
Error in creating the db.gm: "Distance matrix 'X' must be symmetric."

### ISSUE THREAD

**Issue by BioAlgs** [Ecogenomics/GroopM#25]
Reticulating splines
    Dimensionality reduction
Error creating database: db.gm <type 'exceptions.ValueError'>
Unexpected error: <type 'exceptions.ValueError'>
Traceback (most recent call last):
  File "/usr/local/bin/groopm", line 421, in <module>
    GM_parser.parseOptions(args)
  File "/usr/local/lib/python2.7/site-packages/groopm/groopm.py", line 117, in parseOptions
    threads=options.threads)
  File "/usr/local/lib/python2.7/site-packages/groopm/mstore.py", line 359, in createDB
    CT.transformCP()
  File "/usr/local/lib/python2.7/site-packages/groopm/mstore.py", line 1824, in transformCP
    self.shuffleBAMs()
  File "/usr/local/lib/python2.7/site-packages/groopm/mstore.py", line 1916, in shuffleBAMs
    dists = squareform(sq_dists)
  File "/usr/local/lib/python2.7/site-packages/scipy-0.18.1-py2.7-linux-x86_64.egg/scipy/spatial/distance.py", line 1494, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/usr/local/lib/python2.7/site-packages/scipy-0.18.1-py2.7-linux-x86_64.egg/scipy/spatial/distance.py", line 1577, in is_valid_dm
    'symmetric.') % name)   
ValueError: Distance matrix 'X' must be symmetric.

**Comment by transcript** [comment]
#23 looks like the same issue
