### ISSUE TITLE
With forked timbalam/GroopM: stream_ext module not found

### ISSUE THREAD

**Issue by transcript** [Ecogenomics/GroopM#32]
After having issues with the master GroopM, it was suggested to me that I try the newer fork, at github.com/timbalam/groopm .  However, although install seems to go fine (after installing several other Python modules that are not listed anywhere as dependencies), I'm stuck on the need for a Python module called "stream_ext".  

I can't seem to find this anywhere as a part of a standard module.  Can I get this from somewhere?  Is this supposed to be included in the GroopM code and isn't present?

```130 dnanexus@job-FBpXBBj0kJJ9kgXy93B8g397:~/GroopM⟫ groopm2 parse
Traceback (most recent call last):
  File "/usr/local/bin/groopm2", line 56, in <module>
    import groopm
  File "/home/dnanexus/GroopM/groopm/__init__.py", line 53, in <module>
    from cluster import CoreCreator
  File "/home/dnanexus/GroopM/groopm/cluster.py", line 65, in <module>
    import stream
  File "/home/dnanexus/GroopM/groopm/stream.py", line 56, in <module>
    from stream_ext import merge
ImportError: No module named stream_ext```

**Comment by timbalam** [comment]
Hey, thanks for trying the new version. stream_ext is part of GroopM. It's a module written as a Cython extension. I'm not sure why it wouldn't be found, sorry, but maybe that information helps.

**Comment by timbalam** [comment]
Just to check, it looks like cython should compile the extension when the setup script runs I.e  when you run python setup.py build or install or such. You could check the source folder for something like .../GroopM/groopm/stream_ext.pyc? If it worked then this would be I think what the compiled extension would be called.

**Comment by jvollme** [comment]
I have the exact same problem. looking into the groopm subfolder I find ```stream_ext.c```, ```stream_ext.pyx```, ```stream.py``` and ```stream.pyc```.

In my case it may have to do with the fact that i ran "setup.py" without sudo (I am working on a public server without admin rigths, and a global installation is not an option)? I tried adding the path to my ```PYTHONPATH```, but that did not help.
What can i do?

PS: Could you add "tempdir" to the listed dependencies for installing GroopM? The info on the GroopM webpage seems to be outdated...
