### ISSUE TITLE
Problems installing GroopM

### ISSUE THREAD

**Issue by lucaspompeun** [Ecogenomics/GroopM#36]
Help, I've received this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/groopm", line 54, in <module>
    from groopm import groopm
  File "/usr/local/lib/python2.7/dist-packages/groopm/groopm.py", line 56, in <module>
    import cluster
  File "/usr/local/lib/python2.7/dist-packages/groopm/cluster.py", line 94, in <module>
    from scipy.misc import imsave
ImportError: cannot import name imsave
```

run pip to clusters don't fix it

**Comment by lucaspompeun** [comment]
@wwood

**Comment by lucaspompeun** [comment]
@tacaswell @dparks1134 @dparks1134
